# Generated by Django 2.1 on 2018-09-03 13:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0002_auto_20180903_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcase',
            name='webtester',
            field=models.CharField(default=django.utils.timezone.now, max_length=16, verbose_name='测试负责人'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='webcase',
            name='webcasename',
            field=models.CharField(max_length=200, verbose_name='用例名称'),
        ),
        migrations.AlterField(
            model_name='webcase',
            name='webtestresult',
            field=models.BooleanField(verbose_name='测试结果'),
        ),
        migrations.AlterField(
            model_name='webcasestep',
            name='webassertdata',
            field=models.CharField(max_length=50, verbose_name='验证数据'),
        ),
        migrations.AlterField(
            model_name='webcasestep',
            name='webcasename',
            field=models.CharField(max_length=50, verbose_name='测试用例标题'),
        ),
        migrations.AlterField(
            model_name='webcasestep',
            name='webevelement',
            field=models.CharField(max_length=50, verbose_name='控件元素'),
        ),
        migrations.AlterField(
            model_name='webcasestep',
            name='webfindmethod',
            field=models.CharField(max_length=50, verbose_name='定位方式'),
        ),
        migrations.AlterField(
            model_name='webcasestep',
            name='weboptmethod',
            field=models.CharField(max_length=50, verbose_name='操作方法'),
        ),
        migrations.AlterField(
            model_name='webcasestep',
            name='webtestdate',
            field=models.CharField(max_length=50, null=True, verbose_name='测试数据'),
        ),
        migrations.AlterField(
            model_name='webcasestep',
            name='webtestobjname',
            field=models.CharField(max_length=50, verbose_name='测试对象名称描述'),
        ),
        migrations.AlterField(
            model_name='webcasestep',
            name='webteststep',
            field=models.CharField(max_length=50, verbose_name='测试步骤'),
        ),
    ]
