# Generated by Django 2.1 on 2018-09-01 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20180901_1310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '产品名称', 'verbose_name_plural': '产品名称'},
        ),
    ]
