# Generated by Django 2.1 on 2018-09-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webcasestep',
            name='webassertdata',
            field=models.CharField(max_length=100, verbose_name='验证数据'),
        ),
        migrations.AlterField(
            model_name='webcasestep',
            name='webcasename',
            field=models.CharField(max_length=100, verbose_name='测试用例标题'),
        ),
        migrations.AlterField(
            model_name='webcasestep',
            name='webevelement',
            field=models.CharField(max_length=100, verbose_name='控件元素'),
        ),
        migrations.AlterField(
            model_name='webcasestep',
            name='webfindmethod',
            field=models.CharField(max_length=100, verbose_name='定位方式'),
        ),
        migrations.AlterField(
            model_name='webcasestep',
            name='weboptmethod',
            field=models.CharField(max_length=100, verbose_name='操作方法'),
        ),
        migrations.AlterField(
            model_name='webcasestep',
            name='webtestdate',
            field=models.CharField(max_length=100, null=True, verbose_name='测试数据'),
        ),
        migrations.AlterField(
            model_name='webcasestep',
            name='webtestobjname',
            field=models.CharField(max_length=100, verbose_name='测试对象名称描述'),
        ),
        migrations.AlterField(
            model_name='webcasestep',
            name='webteststep',
            field=models.CharField(max_length=100, verbose_name='测试步骤'),
        ),
    ]
